<?php
declare(strict_types=1);

// CorporateBullshitGenerator SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CorporateBullshitGeneratorUtility::setRegistrar(function (CorporateBullshitGeneratorUtility $u): void {
    $u->clean = [CorporateBullshitGeneratorClean::class, 'call'];
    $u->done = [CorporateBullshitGeneratorDone::class, 'call'];
    $u->make_error = [CorporateBullshitGeneratorMakeError::class, 'call'];
    $u->feature_add = [CorporateBullshitGeneratorFeatureAdd::class, 'call'];
    $u->feature_hook = [CorporateBullshitGeneratorFeatureHook::class, 'call'];
    $u->feature_init = [CorporateBullshitGeneratorFeatureInit::class, 'call'];
    $u->fetcher = [CorporateBullshitGeneratorFetcher::class, 'call'];
    $u->make_fetch_def = [CorporateBullshitGeneratorMakeFetchDef::class, 'call'];
    $u->make_context = [CorporateBullshitGeneratorMakeContext::class, 'call'];
    $u->make_options = [CorporateBullshitGeneratorMakeOptions::class, 'call'];
    $u->make_request = [CorporateBullshitGeneratorMakeRequest::class, 'call'];
    $u->make_response = [CorporateBullshitGeneratorMakeResponse::class, 'call'];
    $u->make_result = [CorporateBullshitGeneratorMakeResult::class, 'call'];
    $u->make_point = [CorporateBullshitGeneratorMakePoint::class, 'call'];
    $u->make_spec = [CorporateBullshitGeneratorMakeSpec::class, 'call'];
    $u->make_url = [CorporateBullshitGeneratorMakeUrl::class, 'call'];
    $u->param = [CorporateBullshitGeneratorParam::class, 'call'];
    $u->prepare_auth = [CorporateBullshitGeneratorPrepareAuth::class, 'call'];
    $u->prepare_body = [CorporateBullshitGeneratorPrepareBody::class, 'call'];
    $u->prepare_headers = [CorporateBullshitGeneratorPrepareHeaders::class, 'call'];
    $u->prepare_method = [CorporateBullshitGeneratorPrepareMethod::class, 'call'];
    $u->prepare_params = [CorporateBullshitGeneratorPrepareParams::class, 'call'];
    $u->prepare_path = [CorporateBullshitGeneratorPreparePath::class, 'call'];
    $u->prepare_query = [CorporateBullshitGeneratorPrepareQuery::class, 'call'];
    $u->graphql_body = [CorporateBullshitGeneratorGraphql::class, 'body'];
    $u->graphql_errors = [CorporateBullshitGeneratorGraphql::class, 'errors'];
    $u->result_basic = [CorporateBullshitGeneratorResultBasic::class, 'call'];
    $u->result_body = [CorporateBullshitGeneratorResultBody::class, 'call'];
    $u->result_headers = [CorporateBullshitGeneratorResultHeaders::class, 'call'];
    $u->transform_request = [CorporateBullshitGeneratorTransformRequest::class, 'call'];
    $u->transform_response = [CorporateBullshitGeneratorTransformResponse::class, 'call'];
});
